[general]
name = "cairo-fix"
version = "0.4.0"
fix_version = "1.5.0"

[build]
files = ["cairo.fix", "cairo.image_surface.fix", "cairo.xlib_surface.fix"]
objects = ["cairo.xlib_surface.o"]
preliminary_commands = [
    [
        "make",
        "cairo.xlib_surface.o",
    ],
    [
        "/bin/sh",
        "linker_options.sh",
    ],
]

[build.test]
files = ["test.fix"]

[[dependencies]]
name = "math"
version = "2.0.0"
git = { url = "https://github.com/tttmmmyyyy/fixlang-math.git" }
