[general]
name = "game-of-life"
version = "0.1.1"

[build]
files = ["main.fix"]

[[dependencies]]
name = "cairo-fix"
version = "*"
path = "../../"


[[dependencies]]
name = "time"
version = "0.2.5"
git = { url = "https://github.com/tttmmmyyyy/fixlang-time.git" }


[[dependencies]]
name = "random"
version = "0.1.1"
git = { url = "https://github.com/tttmmmyyyy/fixlang-random.git" }
